### PR TITLE
update app docs links redirect

### PR DESCRIPTION
**Pull request by laurafitzgerald**
**JIRA**
https://issues.jboss.org/browse/AEROGEAR-3560

**What**
Add redirect links for apb docs
- [x] App docs
- [ ] Service docs

@johnfriz

### CODE REVIEW

**Comment by laurafitzgerald** [comment]
@johnfriz

**Comment by laurafitzgerald** [comment]
@johnfriz changes in a new commit.

**Comment by laurafitzgerald** [comment]
@johnfriz I also pushed changes here to update the links that had been merged earlier.

**Comment by wei-lee** [comment]
@laurafitzgerald can we merge this now? What do you mean by "service docs" in the tasks?

**Pull request merged**
